version: "3.9"

services:
  agpred-app:
    container_name: agpred-app
    build:
      context: ./be
    env_file: './be/.env.local'
    volumes:
      - "./:/app:z"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - agpred-net

  agpred-server:
    container_name: agpred-server
    build:
      context: ./nginx/local
    restart: always
    ports:
      - "5000:80"
    depends_on:
      - agpred-app
    networks:
      - agpred-net

networks:
  agpred-net:
    driver: bridge